### ISSUE TITLE
pixelate.py: show help screen when called without options or filename

### ISSUE THREAD

**Issue by Wikinaut** [blackstream-x/pyxelate#107]

**Comment by Wikinaut** [comment]
meh, I don't like to see the "help" output (zero commandline) in a gui window.

Suggestion: just print the same as ```pixelate.py --help```.

**Comment by blackstream-x** [comment]
A misunderstanding: I read „screen“ as „GUI window“.

**Comment by Wikinaut** [comment]
I suggest to also suppress the ERROR message line when no input is given
```
ERROR   ║ Please specify either one of the install options or an image or video file to pixelate.
```
