### ISSUE TITLE
[bug] Very long input filenames break screen layouts, render pyxelate unusable

### ISSUE THREAD

**Issue by Wikinaut** [blackstream-x/pyxelate#114]
![grafik](https://user-images.githubusercontent.com/1151915/141355186-8800af34-268a-47f0-9ac8-efd23c621158.png)

Suggested solution: format filename accordingly

**Comment by blackstream-x** [comment]
Proposed solution: check file name length, and if it’s length is above a yet-to-be-defined threshold (eg 25), cut it in the middle, remove some characters from the middle and join the start and end parts using dots, eg:

very_long_filename_of_a_video.mp4
 ->
very_long_fi…_a_video.mp4
