### ISSUE TITLE
[Info] kdenlive since 21.12 supports motion tracking with pixelation/blurring

### ISSUE THREAD

**Issue by blackstream-x** [blackstream-x/pyxelate#118]
Starting from release 21.12, Kdenlive supports pixelation in combination with motion tracking: https://kdenlive.org/en/2021/12/kdenlive-21-12-is-out/

**Comment by Wikinaut** [comment]
Vielleicht.....

**Comment by Wikinaut** [comment]
Beachte: das Blurring passiert bei kdenlive immer nur im gesamten Rechteck. ("Ellipse" bedeutet nur ein zusätzlich eingefügtes Ellipsoid zur optischen Markierung des Bereiches). Insofern ist Pyxelate besser, denn es kann das Blurring auf die Ellipse beschränken.
