### ISSUE TITLE
Another new workflow: single step: apply area, auto "next" via the next frame button

### ISSUE THREAD

**Issue by Wikinaut** [blackstream-x/pyxelate#84]
Sometimes the path for which the pixelation is needed, is not linear. In these cases, I already had to use four or five segments of pixelation.

Let me suggest - in addition to what works very well :

# single step function
(via the new next/prev frame buttons) navigation (already implemented)

- user moves the area
- user clicks next frame and via the frame navigation pyxelate automagically adds the current area placement as pixelation to that frame
- repeat.

**Comment by blackstream-x** [comment]
Do you still require this? I currently have no idea how to make it intuitive as it seems very special...

**Comment by blackstream-x** [comment]
Not required anymore
